export {default as Header} from './Header/header'
export {default as Projects} from '../container/Projects/projects'
export {default as About} from '../container/About/about'
export {default as Contacts} from '../container/Contact/contacts'
export {default as Services} from '../container/Services/services'